include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - directives_ordering
    - empty_catches
    - file_names
    - library_private_types_in_public_api
    - no_duplicate_case_values
    - null_closures
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - sort_child_properties_last
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - use_build_context_synchronously
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
